// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYCe11tnfxj19wsT4xKALQUSai3viR5lQ',
    appId: '1:903901516033:web:5a728f170ba2d1e7c44b00',
    messagingSenderId: '903901516033',
    projectId: 'chat-app-309bb',
    authDomain: 'chat-app-309bb.firebaseapp.com',
    storageBucket: 'chat-app-309bb.appspot.com',
    measurementId: 'G-F1SLXV5ZR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoXlbuyxv-yg7yPI7AIOSfUqEf31vAPAs',
    appId: '1:903901516033:android:423e9e8d23766850c44b00',
    messagingSenderId: '903901516033',
    projectId: 'chat-app-309bb',
    storageBucket: 'chat-app-309bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATSeCaxbkpHnAfbg7ekRnZp1hRQ-P4Z0g',
    appId: '1:903901516033:ios:daca41a35af12750c44b00',
    messagingSenderId: '903901516033',
    projectId: 'chat-app-309bb',
    storageBucket: 'chat-app-309bb.appspot.com',
    iosClientId: '903901516033-ctvivfbdmk23rd758qsmhivfrq90durt.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatRoom',
  );
}
